export const THEMES = {
  horror: {
    name: 'Horror',
    primaryColor: '#ff0000',
    secondaryColor: '#3a0000',
    subtitleColor: '#ff4444',
    fontFamily: 'Inter',
    vignetteIntensity: 0.8,
    glowIntensity: 0.9,
  },
  mystery: {
    name: 'Mystery',
    primaryColor: '#00ffcc',
    secondaryColor: '#003333',
    subtitleColor: '#66ffcc',
    fontFamily: 'Inter',
    vignetteIntensity: 0.7,
    glowIntensity: 0.8,
  },
  crime: {
    name: 'Crime',
    primaryColor: '#ffcc00',
    secondaryColor: '#332200',
    subtitleColor: '#ffdd44',
    fontFamily: 'Inter',
    vignetteIntensity: 0.6,
    glowIntensity: 0.5,
  },
  emotional: {
    name: 'Emotional',
    primaryColor: '#00ccff',
    secondaryColor: '#002233',
    subtitleColor: '#ffffff',
    fontFamily: 'Inter',
    vignetteIntensity: 0.4,
    glowIntensity: 0.4,
  },
  tiktok: {
    name: 'TikTok Viral',
    primaryColor: '#ffffff',
    secondaryColor: '#000000',
    subtitleColor: '#ffff00',
    fontFamily: 'Inter',
    vignetteIntensity: 0.3,
    glowIntensity: 0.7,
  },
  dark: {
    name: 'Dark Cinematic',
    primaryColor: '#ffffff',
    secondaryColor: '#111111',
    subtitleColor: '#ffffff',
    fontFamily: 'Inter',
    vignetteIntensity: 0.9,
    glowIntensity: 0.2,
  },
  suspense: {
    name: 'Suspense',
    primaryColor: '#e0e0ff',
    secondaryColor: '#0a0a1a',
    subtitleColor: '#e0e0ff',
    fontFamily: 'Inter',
    vignetteIntensity: 0.7,
    glowIntensity: 0.6,
  }
};
